config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :stores do
    member do
      post :comment
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :store, counter_cache: true
end

app/models/store.rb
class Store < ApplicationRecord
  has_many :comments, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/stores_controller.rb
class StoresController < ApplicationController
  before_action :find_store, only: [:edit, :update, :destroy, :comment]

  def index
    @stores = Store.all
  end

  def new
    @store = Store.new
  end

  def create
    @store = Store.new(store_params)

    if @store.save
      # success
      redirect_to stores_path, notice: "新增成功!"
    else
      # fail
      render :new
    end
  end

  def edit
  end

  def update

    if @store.update(store_params)
      # 成功
      redirect_to stores_path, notice: "資料更新成功!"
    else
      # 失敗
      render :edit
    end
  end

  def destroy
    @store.destroy if @store
    redirect_to stores_path, notice: "候選人資料已刪除!"
  end

  def comment
    5.times {p '>>>>>>>'}
    p @store
    p request.remote_ip
    @store.comments.create(ip_address: request.remote_ip) if @store
    @store.save
    redirect_to stores_path, notice: "完成投票!"
  end






  private
  def store_params
    params.require(:store).permit(:name, :address, :introduction)
  end

  def find_store
    @store = Store.find_by(id: params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Protal5</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= notice %>
    <div class="container mt-5">
    <%= yield %>
    </div>
  </body>
</html>

app/views/stores/_form.html.erb
<%= simple_form_for(store) do |f| %>
  <%= f.input :name, label: "姓名" %>
  <%= f.input :address, label: "地址" %>
  <%= f.input :introduction, label: "詳細資料" %>
  <%= f.button :submit %>
<% end %>

app/views/stores/edit.html.erb
<h1>編輯商店</h1>

<%= render "form", store: @store %>

<br />
<%= link_to '回商店列表', stores_path %>

app/views/stores/index.html.erb
<h1>商店列表</h1>

<%= link_to "新增商店", new_store_path %>

<table class="table">
  <thead>
    <tr>
      <td>留言</td>
      <td>候選人姓名</td>
      <td>政黨</td>
      <td>政見</td>
      <td>票數</td>
      <td>處理</td>
    </tr>
  </thead>
  <tbody>
    <% @stores.each do |store| %>
    <tr>
      <td><%= link_to "投給這位", comment_store_path(store), method: "post", data: { confirm: "確定投給這個人?" }, class:"btn btn-primary" %></td>
      <td><%= store.name %></td>
      <td><%= store.address %></td>
      <td><%= store.introduction %></td>
      <td><%= store.comments.size %></td>
      <td>
        <%= link_to "編輯", edit_store_path(store), class:"btn btn-primary" %>
        <%= link_to "刪除", store_path(store), method: "delete", data: { confirm: "確認刪除" }, class:"btn btn-outline-danger" %>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/stores/new.html.erb
<h1>新增商店</h1>

<%= render "form", store: @store %>

<br />
<%= link_to '回商店列表', stores_path %>